### PR TITLE
Update macOS version of the OpenGL sample to match the current state of OpenGL/Glut on Mac

### PR DESCRIPTION
**Pull request by ammbra**
Running the macOS instructions for the [OpenGL sample ](https://github.com/openjdk/jextract/tree/master/samples/opengl) results in failure as Apple discontinued official support for OpenGL (core) and the native `libGL.dylib` doesn't exist anymore. 
Below is the situation in details:

* running [compile.sh](https://github.com/openjdk/jextract/blob/master/samples/opengl/compile.sh) or [compilesource.sh](https://github.com/openjdk/jextract/blob/master/samples/opengl/compilesource.sh) will produce Java code that compiles.
* attempting to run [run.sh](https://github.com/openjdk/jextract/blob/master/samples/opengl/run.sh) will result in error 
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at Teapot.main(Teapot.java:75)
Caused by: java.lang.IllegalArgumentException: Cannot open library: libGL.dylib
	at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:314)
	at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:266)
	at opengl.glut_h_3.<clinit>(glut_h_3.java:58)
	... 1 more
```

But OpenGL and Glut frameworks are still pre-installed with Apple development tools. This PR fixes the above error by referencing to the OpenGL and Glut frameworks available with Xcode:
* `jextract` finds the header files via [compile_flags.txt]([[compile.sh](https://github.com/openjdk/jextract/blob/master/samples/opengl/compile_flags.txt)](https://github.com/openjdk/jextract/blob/master/samples/opengl/compile_flags.txt)
* At runtime, the generated header class finds the shared libraries thanks to providing `-l :/System/Library/Frameworks/GLUT.framework/Versions/Current/GLUT` and `-l -l :/System/Library/Frameworks/OpenGL.framework/Versions/Current/OpenGL` to `jextract` command.
*  A small side effect: the `Teapot.java` class is updated to use generated `glutDisplayFunc$func` and `glutIdleFunc$func`classes. Generated code varies depending on OpenGL/Glut distribution used. 

- [x] Tested locally on macOS Sonoma 14.4.1 with JDK 22 and using [jextract binaries](https://jdk.java.net/jextract/).
- [ ] The code from `Teapot.java` is common for all the operating systems. Additional tests should be done on Windows/Linux.

**Reviewers**
[Athijegannathan Sundararajan](https://openjdk.org/census#sundar) (@sundararajana - Committer)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed (no review required)

### Reviewers
 * [Athijegannathan Sundararajan](https://openjdk.org/census#sundar) (@sundararajana - Committer) ⚠️ Review applies to [536a0bb7](https://git.openjdk.org/jextract/pull/245/files/536a0bb7c3f920cdc9c5117d28a0f1ff4e405cf9)
 * [Maurizio Cimadamore](https://openjdk.org/census#mcimadamore) (@mcimadamore - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jextract.git pull/245/head:pull/245` \
`$ git checkout pull/245`

Update a local copy of the PR: \
`$ git checkout pull/245` \
`$ git pull https://git.openjdk.org/jextract.git pull/245/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 245`

View PR using the GUI difftool: \
`$ git pr show -t 245`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jextract/pull/245.diff">https://git.openjdk.org/jextract/pull/245.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jextract/pull/245#issuecomment-2127081431)

### CODE REVIEW

**Comment by mcimadamore** [comment]
Looks good - I'll leave the last word to @sundararajana as I don't have a macos to test it on :-)

**Comment by sundararajana** [comment]
Please add the following line to the compilesource.sh script

javac --source=22 -d . opengl/*.java

jextract only generates source files. we need to compile before using run.sh. The comtpilesource.sh scripts in all other samples have javac instruction.

**Review by sundararajana — APPROVED** [review]
LGTM

**Comment by sundararajana** [comment]
> Looks good - I'll leave the last word to @sundararajana as I don't have a macos to test it on :-)

I verified that the sample works fine on my MacOS/intel machine after applying the current patch

**Comment by sundararajana** [comment]
The -l paths in compilesource.sh may be changed as follows:

$ cat compilesource.sh
jextract -t opengl -l :/System/Library/Frameworks/GLUT.framework/GLUT \
  -l :/System/Library/Frameworks/OpenGL.framework/OpenGL \
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/GLUT.framework/Headers/glut.h

javac --source=22 -d . opengl/*.java

**Comment by ammbra** [comment]
Great finding 😄 ! Thank you. I shortened the path, tested and delivered a new commit.

**Review by mcimadamore — APPROVED** [review]
Looks great - thanks!

**Pull request closed without merging**
