### PR TITLE
Code formatting

### PR DESCRIPTION
**Pull request by minborg**
xxxx$MH methods should be declared private to reduce cluttering in end users' IDEs and elsewhere.
 
 This PR also solves esthetic issues in the generated code.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed (no review required)

### Reviewers
 * [Athijegannathan Sundararajan](https://openjdk.org/census#sundar) (@sundararajana - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jextract pull/67/head:pull/67` \
`$ git checkout pull/67`

Update a local copy of the PR: \
`$ git checkout pull/67` \
`$ git pull https://git.openjdk.org/jextract pull/67/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 67`

View PR using the GUI difftool: \
`$ git pr show -t 67`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jextract/pull/67.diff">https://git.openjdk.org/jextract/pull/67.diff</a>

</details>

### CODE REVIEW

**Comment by sundararajana** [comment]
We want to expose native method handles to the user - so that s/he can adapt it rather than just confined to use our wrapper method.

**Comment by minborg** [comment]
There is a middle way where we could put the native method handles in an inner class (e.g. MethodHandles) exposing these methods for the casual user while still keeping the most used API clean.

Before: `foo_h.bar$MH()`
After: `foo_h.MethodHandles.bar()`

**Review by sundararajana — APPROVED** [review]
LGTM

**Pull request closed without merging**
