### PR TITLE
Upgrade to Gradle 8.0.2

### PR DESCRIPTION
**Pull request by yuzawa-san**
Upgrade to the most recent gradle version. The prior version (7.3.3) did not support Java versions after 17 per https://docs.gradle.org/current/userguide/compatibility.html This change will allow user to build jextract on Java 19. I had to make sure I had a JDK 17 around for the gradle, set the JAVA_HOME, then make sure I had another proper JDK to bootstrap the build. Additionally, I added a gradle wrapper validation github action to ensure the integrity of the wrapper.

Question: is "master" not longer the default branch in this repo? Should these changes to into master and then ported to the various versions branches? Let me know how you may want to proceed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed (no review required)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jextract pull/110/head:pull/110` \
`$ git checkout pull/110`

Update a local copy of the PR: \
`$ git checkout pull/110` \
`$ git pull https://git.openjdk.org/jextract pull/110/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 110`

View PR using the GUI difftool: \
`$ git pr show -t 110`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jextract/pull/110.diff">https://git.openjdk.org/jextract/pull/110.diff</a>

</details>

### CODE REVIEW

**Comment by JornVernee** [comment]
Thanks for the patch!

I'm testing it out on my Windows machine but it seems like there is an issue with this version of gradle:

```
> .\gradlew clean build
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Error while evaluating property 'javaCompiler' of task ':compileJava'.
   > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
      > The configured executable does not exist (<path to jdk>\bin\javac)
```

It seems like we need to append `.exe` to the javac executable path explicitly now for Windows to work:

```
diff --git a/build.gradle b/build.gradle
index c349359..45bc921 100644
--- a/build.gradle
+++ b/build.gradle
@@ -32,6 +32,7 @@ def clang_include_dir = "${llvm_home}/lib/clang/${clang_version}/include"
 checkPath(clang_include_dir)
 def os_lib_dir = Os.isFamily(Os.FAMILY_WINDOWS)? "bin" : "lib"
 def os_script_extension = Os.isFamily(Os.FAMILY_WINDOWS)? ".bat" : ""
+def os_exe_extension = Os.isFamily(Os.FAMILY_WINDOWS)? ".exe" : ""
 def libclang_dir = "${llvm_home}/${os_lib_dir}"
 checkPath(libclang_dir)

@@ -43,7 +44,7 @@ compileJava {
     options.release = 21
     options.compilerArgs << "--enable-preview"
     options.fork = true
-    options.forkOptions.executable = "${jdk21_home}/bin/javac"
+    options.forkOptions.executable = "${jdk21_home}/bin/javac${os_exe_extension}"
 }

 jar {
 ```
 
 ---
 
> Question: is "master" not longer the default branch in this repo? Should these changes to into master and then ported to the various versions branches? Let me know how you may want to proceed.

The `master` branch is targeting the Java 19 API, which is currently the latest release version. The panama branch targets the API we have in the panama-foreign repo, which is Java 21 now. I don't see support for 21 in the Gradle compatibility matrix though.

Which version of jextract are you interested in building?

**Comment by yuzawa-san** [comment]
@JornVernee I found your relative paths bug https://github.com/gradle/gradle/issues/20837 and also I found https://github.com/gradle/gradle/pull/23887. The good news is that both are slated for gradle 8.1 which is coming soon so I suppose I can hold off until that is released. I will add your exe extension patch at that time.

I was using java 19 to bootstrap the jextract build for java 20 (and will soon likely build for java 21). If I branch off and PR into master could the changes get applied to the jdk* and panama branches? I guess minimally the new gradle version should be in jdk20 (and panama branches).

**Comment by JornVernee** [comment]
> If I branch off and PR into master could the changes get applied to the jdk* and panama branches?

This doesn't happen automatically, unfortunately, we'd need 3 separate PRs.

> I guess minimally the new gradle version should be in jdk20 (and panama branches).

Yes, that sounds like a good idea.

**Pull request closed without merging**
