### PR TITLE
7903134: Improve error reporting in jextract gradle build

### PR DESCRIPTION
**Pull request by JornVernee**
Improve error reporting around missing LLVM paths in jextract gradle build.

This patch tries to detect missing paths and throw a descriptive error, instead of a more cryptic one.

I've also added the `.idea` folder to the `.gitignore` file.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [CODETOOLS-7903134](https://bugs.openjdk.java.net/browse/CODETOOLS-7903134): Improve error reporting in jextract gradle build

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.java.net/census#mcimadamore) (@mcimadamore - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jextract pull/8/head:pull/8` \
`$ git checkout pull/8`

Update a local copy of the PR: \
`$ git checkout pull/8` \
`$ git pull https://git.openjdk.java.net/jextract pull/8/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8`

View PR using the GUI difftool: \
`$ git pr show -t 8`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jextract/pull/8.diff">https://git.openjdk.java.net/jextract/pull/8.diff</a>

</details>

### CODE REVIEW

**Review by mcimadamore — COMMENTED** [review]
Looks good - should we take the change and also rename libclang_home to llvm_home?

**Comment by JornVernee** [comment]
> Looks good - should we take the change and also rename libclang_home to llvm_home?

Good idea. Did that.

**Review by mcimadamore — APPROVED** [review]
Looks good, thanks!

**Pull request closed without merging**
